#!/usr/bin/env ruby

require 'bundler'
require 'pry'
require 'taglib'
require 'pathname'
require 'fileutils'

path = ARGV.first.strip.gsub(/\\/, '')
out_dir = File.expand_path("~/Documents/serato_out/")

FileUtils.mkdir_p(out_dir) unless File.exists?(out_dir)

TagLib::MPEG::File.open(path) do |f|
  title = f.tag.title
  v2    = f.id3v2_tag

  v2.frame_list('GEOB').each do |g|
    if g.description =~ /serato/i
      output_path = "#{out_dir}/#{title}/#{g.description}"
      puts output_path

      FileUtils.mkdir_p(File.dirname(output_path)) unless File.exists?(File.dirname(output_path))

      ::File.open(output_path, "w+") { |ff| ff.write g.object }
    end
  end
end
